# setup webservers
---
  - hosts: webservers
    become: true
    tasks:
      - name: update all packages to the lastest version
        yum: name=* state=latest

      - name: install apache webserver
        yum: name=apache2 state=present

      - name: delete original index.html file
        file: path=/var/www/html/index.html state=absent

      - name: create new index.html file
        lineinfile:
          create: yes
          path: /var/www/html/index.html
          line: <html> Hello from server1</html>
        notify: start apache
      
    handlers:
      - name: start apache
        service: name=apache2 state=started

  - hosts: bastions
    become: true
    tasks:
      - name: update all packages to the lastest version
        yum: 
          name: * 
          state: latest

      - name: install apache webserver
        yum: 
          name: apache2
          state: present

      - name: delete original index.html file
        file: path=/var/www/html/index.html state=absent

      - name: create new index.html file
        lineinfile:
          create: yes
          path: /var/www/html/index.html
          line: <html> Hello from server2</html>
        notify: start apache
      
    handlers:
      - name: start apache
        service: name=apache2 state=started
       